version: "3.9"
services:
  next-app:
    image: node:lts
    working_dir: /app
    command: npx next dev -p 4000
    networks:
      - overlay
    volumes:
      - ".:/app"
    ports:
      - "4000:4000"

networks:
  overlay:
